export enum ActionType {
  CREATE_USER = 'create_user',
  CREATE_USER_SUCCESS = 'create_user_success',
  CREATE_USER_ERROR = 'create_user_error',
  LOGIN_USER = 'login_user',
  LOGIN_USER_SUCCESS = 'login_user_success',
  LOGIN_USER_ERROR = 'login_user_error',
  LOGOUT_USER = 'logout_user',
  LOGIN_GUEST_SUCCESS = 'login_guest_success',
  LOAD_BOARD = 'load_board',
  LOAD_BOARD_SUCCESS = 'load_board_success',
  LOAD_BOARD_ERROR = 'load_board_error',
  CLEAR_BOARD = 'clear_board',
  CREATE_LIST = 'create_list',
  UPDATE_LIST = 'update_list',
  COPY_LIST = 'copy_list',
  DELETE_LIST = 'delete_list',
  CLEAR_LIST = 'clear_list',
  REORDER_LIST = 'reorder_list',
  CREATE_TASK = 'create_task',
  UPDATE_TASK = 'update_task',
  DELETE_TASK = 'delete_task',
  MOVE_TASK = 'move_task',
  REORDER_TASK = 'reorder_task',
}
